### ISSUE TITLE
OpenShift Elastisearch Operator => 'namespaces "openshift-operators-redhat" not found' error 

### ISSUE THREAD

**Issue by sjbylo** [redhat-cop/gitops-catalog#54]
1. Getting error:
```
$ oc apply -k https://github.com/redhat-cop/gitops-catalog/elastisearch-operator/overlays/stable
Error from server (NotFound): error when creating "https://github.com/redhat-cop/gitops-catalog/elastisearch-operator/overlays/stable": namespaces "openshift-operators-redhat" not found
```

Works if you change the namespace by removing "-redhat" from all the following files:
```
gitops-catalog/elastisearch-operator/overlays/stable/kustomization.yaml
gitops-catalog/elastisearch-operator//overlays/5.0/kustomization.yaml
gitops-catalog/elastisearch-operator//overlays/4.6/kustomization.yaml
gitops-catalog/elastisearch-operator//base/kustomization.yaml
gitops-catalog/elastisearch-operator//base/elastisearch-subscription.yaml
```

2. Also, suggest to rename the dir from "elastisearch" to "elasticsearch" (add the 'c')

**Comment by pittar** [comment]
Thanks @sjbylo 
1. It looks like the base `kustomization.yaml` file specifies the namespace `openshift-operators-redhat` (as recommended by the operator install instructions), however, there is no namespace yaml file provided.  I think it would be best to include the namespace resource in the base dir, since it is the recommended namespace.  For now, you can pre-create the `openshift-operators-redhat` namespace, or include a namespace resource in your own repo and simply include the catalog overlay as a base in your `kustomization.yaml` file.

2. I agree, the directory name should be updated to include the `c`.

I'll make the updates, test them out, then submit a PR.

**Comment by pittar** [comment]
@sjbylo PR for part 1 of this issue:
https://github.com/redhat-cop/gitops-catalog/pull/55

**Comment by pittar** [comment]
Fixed with PR https://github.com/redhat-cop/gitops-catalog/pull/60

Next step will be rename the base folder.  There's another issue opened for that, so closing this one.
